package com.hereliesaz.cuedetat.ui.theme

import androidx.compose.ui.graphics.Color

// --- Dark Theme: "Mint Night" ---
val dark_primary = Color(0xFF53DE8C)
val dark_onPrimary = Color(0xFF003919)
val dark_primaryContainer = Color(0xFF005227)
val dark_onPrimaryContainer = Color(0xFF72FBA4)
val dark_secondary = Color(0xFFB8CCB8)
val dark_onSecondary = Color(0xFF233427)
val dark_secondaryContainer = Color(0xFF394B3C)
val dark_onSecondaryContainer = Color(0xFFD4E8D3)
val dark_tertiary = Color(0xFFA1CED5)
val dark_onTertiary = Color(0xFF01363D)
val dark_tertiaryContainer = Color(0xFF1D4D54)
val dark_onTertiaryContainer = Color(0xFFBDEAF1)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_background = Color(0xFF1A1C1A)
val dark_onBackground = Color(0xFFE2E3DE)
val dark_surface = Color(0xFF1A1C1A)
val dark_onSurface = Color(0xFFE2E3DE)
val dark_outline = Color(0xFF8C938A)

// --- Light Theme: "Mint Day" ---
val light_primary = Color(0xFF006D35)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF72FBA4)
val light_onPrimaryContainer = Color(0xFF00210C)
val light_secondary = Color(0xFF506352)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD4E8D3)
val light_onSecondaryContainer = Color(0xFF0E1F12)
val light_tertiary = Color(0xFF38656C)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFBDEAF1)
val light_onTertiaryContainer = Color(0xFF001F24)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_background = Color(0xFFFCFDF7)
val light_onBackground = Color(0xFF1A1C1A)
val light_surface = Color(0xFFFCFDF7)
val light_onSurface = Color(0xFF1A1C1A)
val light_outline = Color(0xFF727970)