package com.hereliesaz.cuedetat.ui.theme

import androidx.compose.ui.graphics.Color

// Expressive Light Theme Colors
val expressive_light_primary = Color(0xFF9C423A)
val expressive_light_onPrimary = Color(0xFFFFFFFF)
val expressive_light_primaryContainer = Color(0xFFFFDAD6)
val expressive_light_onPrimaryContainer = Color(0xFF410002)
val expressive_light_secondary = Color(0xFF775653)
val expressive_light_onSecondary = Color(0xFFFFFFFF)
val expressive_light_secondaryContainer = Color(0xFFFFDAD6)
val expressive_light_onSecondaryContainer = Color(0xFF2C1513)
val expressive_light_tertiary = Color(0xFF725C2E)
val expressive_light_onTertiary = Color(0xFFFFFFFF)
val expressive_light_tertiaryContainer = Color(0xFFFEDE95)
val expressive_light_onTertiaryContainer = Color(0xFF261A00)
val expressive_light_error = Color(0xFFBA1A1A)
val expressive_light_onError = Color(0xFFFFFFFF)
val expressive_light_background = Color(0xFFFFF8F7)
val expressive_light_onBackground = Color(0xFF231918)
val expressive_light_surface = Color(0xFFFFF8F7)
val expressive_light_onSurface = Color(0xFF231918)
val expressive_light_outline = Color(0xFF857371)

// Expressive Dark Theme Colors
val expressive_dark_primary = Color(0xFFFFB4AC)
val expressive_dark_onPrimary = Color(0xFF5F1511)
val expressive_dark_primaryContainer = Color(0xFF7D2B25)
val expressive_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val expressive_dark_secondary = Color(0xFFE7BDB8)
val expressive_dark_onSecondary = Color(0xFF442927)
val expressive_dark_secondaryContainer = Color(0xFF5D3F3C)
val expressive_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val expressive_dark_tertiary = Color(0xFFE1C27B)
val expressive_dark_onTertiary = Color(0xFF402E04)
val expressive_dark_tertiaryContainer = Color(0xFF594519)
val expressive_dark_onTertiaryContainer = Color(0xFFFEDE95)
val expressive_dark_error = Color(0xFFFFB4AB)
val expressive_dark_onError = Color(0xFF690005)
val expressive_dark_background = Color(0xFF1A1110)
val expressive_dark_onBackground = Color(0xFFF1DEDC)
val expressive_dark_surface = Color(0xFF1A1110)
val expressive_dark_onSurface = Color(0xFFF1DEDC)
val expressive_dark_outline = Color(0xFFA08C8A)
